site_name: Jetpack Android Template
repo_name: Jetpack-Compose-Starter
repo_url: https://github.com/atick-faisal/Jetpack-Compose-Starter

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.view

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk

plugins:
  - search
  - tags

# nav:
#   - 'Home':
#       - 'Home': index.md
#       - 'Website': https://atick.dev
#   - 'Core':
#       - 'Android': core/android/index.md
#       - 'UI': core/ui/index.md

copyright: Copyright &copy; 2016 - 2020 Martin Donath