name: Docs

on:
  push:
    branches:
      - feature/documentation
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Services
        run: |
          touch app/google-services.json
          echo "${CONTENT// /}" | base64 --decode > app/google-services.json
        env:
          CONTENT: ${{ secrets.GOOGLE_SERVICES }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Generate Docs
        run: |
          pip install mkdocs
          ./gradlew dokkaGfmMultiModule
          mv ./build/dokka/htmlMultiModule docs
          mkdocs gh-deploy
          
        
